config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do #手動サインアウト用
    get '/users/sign_out' => 'devise/sessions#destroy'
  end      

  root to: 'kaigos#index'
  resources :kaigos, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/degree_care_of.rb
class DegreeCareOf  < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '支援なし' },
    { id: 3, name: '要支援1' },
    { id: 4, name: '要支援2' },
    { id: 5, name: '要介護1' },
    { id: 6, name: '要介護2' },
    { id: 7, name: '要介護3' },
    { id: 8, name: '要介護4' },
    { id: 9, name: '要介護5' }
  ]

  include ActiveHash::Associations
  has_many :user
end

app/models/kaigo.rb
class Kaigo < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :kt

  validates :date, presence: true
end

app/models/kt.rb
class Kt < ActiveHash::Base
  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: '36.0以下'},
    { id: 3, name: '36.1'},
    { id: 4, name: '36.2'},
    { id: 5, name: '36.3'},
    { id: 6, name: '36.4'},
    { id: 7, name: '36.5'},
    { id: 8, name: '36.6'},
    { id: 9, name: '36.7'},
    { id: 10, name: '36.8'},
    { id: 11, name: '36.9'},
    { id: 12, name: '37.0'},
    { id: 13, name: '37.1'},
    { id: 14, name: '37.2'},
    { id: 15, name: '37.3'},
    { id: 16, name: '37.4'},
    { id: 17, name: '37.5'},
    { id: 18, name: '37.6'},
    { id: 19, name: '37.7'},
    { id: 20, name: '37.8'},
    { id: 21, name: '37.9'},
    { id: 22, name: '38.0以上'}
  ]

  include ActiveHash::Associations
  has_many :kaigos

  end

app/models/sex.rb
class Sex  < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '男性' },
    { id: 3, name: '女性' }
  ]

  include ActiveHash::Associations
  has_many :user
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :degree_of_care, optional: true
  belongs_to :sex
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :degree_care_of_id, numericality: { other_than: 1, message:"can't be blank" }
  validates :sex_id, numericality: { other_than: 1, message:"can't be blank" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]    
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name , :last_name ,:sex_id , :degree_care_of_id, :birthday , :first_name_kana , :last_name_kana ])
  end
end

app/controllers/kaigos_controller.rb
class KaigosController < ApplicationController
  def index
    @kaigos = Kaigo.all
  end

  def new
    @kaigo = Kaigo.new
  end

  def create
    @kaigo = Kaigo.new(kaigo_params)
    if @kaigo.save
      redirect_to_ root_path
    else
      render :new
    end
  end

  private

  def kaigo_params
    params.require(:kaigo)
          .permit(:date, :kt_id, :bp1, :bp2, :pulse, :breakfast_amount_id, :lunch_amount_id,
                  :supper_amount_id, :bath_id, :sleeping_id, :urinary_id, :defecation_id, :recode)
          .merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kaigos_helper.rb
module KaigosHelper
end

app/views/kaigos/index.html.erb
<%= render "shared/header" %>
<div class="main">
 <div class=head>
   <h2 class="wellcom">ようこそ 山田花子さん</h2>
   <div class="form" id="form-1" >
    <%=link_to '日々の記録を入力する', new_kaigo_path, class: "form" %>
   </div>
 </div>
 <div class="contents-back">
  <table class="contents-main">
    <tr>
      <th>日付</th>
      <th>体温</th>
      <th>血圧</th>
      <th>脈拍</th>
      <th>朝食</th>
      <th>昼食</th>
      <th>夕食</th>
      <th>入浴</th>
      <th>睡眠時間</th>
      <th>トイレ回数</th>
      <th>排便</th>
      <th>記録</th>
    </tr>
    <tr>
      <td>7/7</td>
      <td>36.5</td>
      <td>123/67</td>
      <td>67</td>
      <td>10割</td>
      <td>10割</td>
      <td>10割</td>
      <td>済</td>
      <td>6時間</td>
      <td>５回</td>
      <td>あり</td>
      <td>あり</td>
    </tr>
    <tr>
      <td>7/6</td>
      <td>36.5</td>
      <td>123/67</td>
      <td>67</td>
      <td>10割</td>
      <td>10割</td>
      <td>10割</td>
      <td>済</td>
      <td>6時間</td>
      <td>５回</td>
      <td>あり</td>
      <td>あり</td>
    </tr>
    <tr>
      <td>7/5</td>
      <td>36.5</td>
      <td>123/67</td>
      <td>67</td>
      <td>10割</td>
      <td>10割</td>
      <td>10割</td>
      <td>済</td>
      <td>6時間</td>
      <td>５回</td>
      <td>あり</td>
      <td>あり</td>
    </tr>
    <tr>
      <td>7/4</td>
      <td>36.5</td>
      <td>123/67</td>
      <td>67</td>
      <td>10割</td>
      <td>10割</td>
      <td>10割</td>
      <td>済</td>
      <td>6時間</td>
      <td>５回</td>
      <td>あり</td>
      <td>あり</td>
    </tr>
    <tr>
      <td>7/3</td>
      <td>36.5</td>
      <td>123/67</td>
      <td>67</td>
      <td>10割</td>
      <td>10割</td>
      <td>10割</td>
      <td>済</td>
      <td>6時間</td>
      <td>５回</td>
      <td>あり</td>
      <td>あり</td>
    </tr>
    <tr>
      <td>7/2</td>
      <td>36.5</td>
      <td>123/67</td>
      <td>67</td>
      <td>10割</td>
      <td>10割</td>
      <td>10割</td>
      <td>済</td>
      <td>6時間</td>
      <td>５回</td>
      <td>あり</td>
      <td>あり</td>
    </tr>
    <tr>
      <td>7/1</td>
      <td>36.5</td>
      <td>123/67</td>
      <td>67</td>
      <td>10割</td>
      <td>10割</td>
      <td>10割</td>
      <td>済</td>
      <td>6時間</td>
      <td>５回</td>
      <td>あり</td>
      <td>あり</td>
    </tr>
  </table>
 </div>
</body>

app/views/kaigos/new.html.erb
<%= form_with model: @kaigo, url:kaigos_path, local: true do |f| %>
<div class="form-wrap">
  <div class="form-heder">
    <h1 class="form-header-text">
     日々の記録の入力
    </h1>
  </div>

  <%# エラーメッセージ%>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">日付</label>
      <%= f.date_field :date, class: "form-calender" %>
      <span class="indispensable">必須</span>
    </div>
    <div class="form-text-wrap">
      <label class="form-text">体温</label>
      <%= f.collection_select(:kt_id, Kt.all, :id, :name,{}, {class:"from-kt"})%>
    </div>
    <div class="form-text-wrap"> 
      <div class="form-wrap">
        <label class="form-text=wrap">最高血圧</label>
        <%=f.text_field :bp1, class:"form-bp1" %>
        <label class="form-text=wrap">最低血圧</label>
        <%=f.text_field :bp2, class:"form-bp2" %>
      </div>
    </div>
    <div class="form-text-wrap">
      <div class="form-wrap">
        <label class="form-text-wra">脈拍</label>
        <%=f.text_field :pulse, class:"form-pulse" %>
      </div>
    </div>
    <div class="form-text-wrap">
      <div class="form-wrap">
        <label class="form-text">朝食量</label>
      </div>
    </div>
    <>

  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KaigoApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :css %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header class="page-header wrapper">
  <h2 class="wellcom">ようこそ kaigo appへ</h2>
  <nav>
    <ul class="main-nav">
      <% if user_signed_in? %>
        <li><%= link_to current_user.lasr_name"さん", "#", class: "user-name" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"%></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "singup" %></li>
      <% end %>
    </ul>
  </nav>
</header>